services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db               # persistent data
      - ./mongo-init:/docker-entrypoint-initdb.d:ro  # init scripts
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s